title:<p align"center"> PRANEETH REDDY
logo: /assets/img/logo.png
description: I am a data scientist handling projects related to education sector mostly into technical side.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
